server:
  port: 8080

spring: 
  profiles.active: dev,swagger

eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  
hystrix: 
  command: 
    default: 
      execution.isolation.thread.timeoutInMilliseconds: 10000
